![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/330px-NumPy_logo_2020.svg.png)

https://numpy.org/doc/

In [5]:
# numpy import
import numpy as np

### numpy 배열 만들기

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

 - axis : 배열의 축  ex) x(1), y(0)
 - rank : 축의 개수, ndim이랑 같음  ex) x, y 2차원 배열
 - shape: 축의 길이, 배열의 크기  ex) (4, 3)

In [ ]:
# 리스트 -> numpy 배열
a = [1,2,3,4,5,6,7,8,9,0] # 1차원
b = [[1,2,3,4,5], [6,7,8,9,0]] # 2차원
c = [[[1,2,3],[4,5,6], [7,8,9]]] # 3차원

a_np = np.array(a)
b_np = np.array(b)
c_np = np.array(c)

print(a_np)
print(b_np)
print(c_np)

In [ ]:
# 배열 차원
print('ndim / rank')
print(a_np.ndim)
print(b_np.ndim)
print(c_np.ndim)
print()

# 배열 크기 - 튜플
print('shape')
print(a_np.shape) # (x, )
print(b_np.shape) # (x, y)
print(c_np.shape) # (x, y, z)
print()

# 배열 요소 자료형 - 배열은 한가지의 자료형만 가진다.
print('dtype')
print(a_np.dtype)
print(b_np.dtype)
print(c_np.dtype)
print()

### Reshape (배열 재배치)
 - 요소의  수와 규칙에 영향을 주지 않는 범위 내에서 변경 가능
 - (n, -1) 또는 (-1, n)으로 사용 가능, -1을 자동으로 크기 계산하여 지정됨

In [ ]:
# 1차원 -> 2차원
re_a_np = a_np.reshape(2, 5)
print(a_np)
print('-'*30)
print(re_a_np)
print()

# 2차원 -> 1차원
re_b_np = b_np.reshape(10, )
print(b_np)
print('-'*30)
print(re_b_np)
print()

# 2차원 -> 2차원 / (2, 5) -> (5, 2)
re_b_np = b_np.reshape(5, 2) # == re_b_np = b_np.reshape(5, -1) == re_b_np = b_np.reshape(-1, 2)
print(b_np)
print('-'*30)
print(re_b_np)

## 배열 index
 - list index와 유사
 - array[행, 열] 형태도 특정 요소 조회

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.png?raw=true' width=800 align="left"/>

In [50]:
np_idx = np.array([[1, 2, 3], 
                    [4, 5, 6],
                    [7, 8, 9]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np_idx)
print()

### 특정 요소 idx 조회
print(np_idx[0, 1]) # 1차원
print(np_idx[[0], [1]]) # 2차원
print()


### 행 조회
# 행 하나 조회
# [0] : [[0]] 비교
print(np_idx[0, :]) # : 생략 가능
print(np_idx[0]) # 1차원
print(np_idx[[0]]) # 2차원
print()

# 2개 이상 행 조회
print(np_idx[[0,2]])
print()


### 열 조회
# 열 하나 조회 
# [:, 0] : [:, [0]] 비교
print(np_idx[:, 0]) # : 생략 불가, 1차원
print(np_idx[:, [0]]) # 2차원
print()

# 2개 이상 열 조회
print(np_idx[:, [0,2]])
print()


### 행/열 조회
print(np_idx[[0,2],[0,2]]) # [0, 0], [2, 2] 요소 조회
print(np_idx[[0,1,2],[2,1,0]]) # [0, 2], [1, 1], [2, 0] 요소 조회

### 배열 slicing
 - list slice와 유사
 - n행 ~ m행 / n열 ~ m열 조회
 - [n:m] : n 부터 m-1 까지

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B12.png?raw=true' width=800 align="left"/>

In [ ]:
print(np_idx)
print()

# 행 슬라이싱 [n:m, x]
print(np_idx[0:2, :]) # : 생략 가능
print(np_idx[0:2])
print()

# 열 슬라싱 [x, n:m]
print(np_idx[:, 0:2]) # : 생략 불가
print()
print(np_idx[1, 0:2]) # 특정 행의 열 슬라이싱
print()
print(np_idx[0:2, 0:2]) # 범위 행의 열 슬라이싱
print()

# n 부터 끝까지 슬라이싱
print(np_idx[1:, 0:])

### 조건 조회
 - 조회 결과는 1차원 배열이 된다

In [ ]:
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

print(score)
print()

print(score[score >= 90])
print()

# & 또는 | 연산을 사용하는 경우 각 조건을 ()로 묶어야 한다. (score >= 90)  (score < 95)
print(score[(score >= 90) & (score < 95)])

#### numpy.where(조건, 참, 거짓)
 - 조건 : True, False 조건이 되도록 표현
 - 참 : 조건이 참 일때 값
 - 거짓 : 조건이 거짓 일때 값

In [65]:
wh_score = np.where(score >= 90, score, 90 - score)
print(wh_score)

[[12 91  6  1 93 25]
 [ 8  3 96 11 91 17]]


### 배열 연산
 - +, -, *, /, **
 - 행열 연산

In [ ]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print('x')
print(x)
print('y')
print(y)
print()

# +
print('+')
print(x + y)
print(np.add(x, y))
print(x+10)
print()

# -
print('-')
print(x - y)
print(np.subtract(x, y))
print(x-10)
print()

# *
print('*')
print(x * y)
print(np.multiply(x, y))
print(x*10)
print()

# /
print('/')
print(x / y)
print(np.divide(x, y))
print(x/10)
print()


# **
print('**')
print(x ** y)
print(np.power(x, y))
print(x**2)
print()


### 배열 집계
 - sum, max, min, mean, std
 - axis = 0 : 열 기준 집계 / axis = 1 : 행 기준 집계
 - axis 생략 시 전체 집계
 - np.sum() or array.sum() 형태로 사용

In [ ]:
np_total = np.array([[1,5,7],[2,3,8]])

In [ ]:
print(np_total)
print()

### sum()
# 전체
print(np_total.sum())
print(np.sum(np_total))
print()

# axis = 0 : 열 합계
print(np_total.sum(axis=0))
print(np.sum(np_total, axis=0))
print()

# axis = 1 : 행 합계
print(np_total.sum(axis=1))
print(np.sum(np_total, axis=1))
print()

In [ ]:
print(np_total)
print()

### max()
# 전체
print(np_total.max())
print(np.max(np_total))
print()

# axis = 0 : 열 합계
print(np_total.max(axis=0))
print(np.max(np_total, axis=0))
print()

# axis = 1 : 행 합계
print(np_total.max(axis=1))
print(np.max(np_total, axis=1))
print()

In [ ]:
print(np_total)
print()

### min()
# 전체
print(np_total.min())
print(np.min(np_total))
print()

# axis = 0 : 열 합계
print(np_total.min(axis=0))
print(np.min(np_total, axis=0))
print()

# axis = 1 : 행 합계
print(np_total.min(axis=1))
print(np.min(np_total, axis=1))
print()

In [ ]:
print(np_total)
print()

### mean()
# 전체
print(np_total.mean())
print(np.mean(np_total))
print()

# axis = 0 : 열 합계
print(np_total.mean(axis=0))
print(np.mean(np_total, axis=0))
print()

# axis = 1 : 행 합계
print(np_total.mean(axis=1))
print(np.mean(np_total, axis=1))
print()

In [ ]:
print(np_total)
print()

### std()
# 전체
print(np_total.std())
print(np.std(np_total))
print()

# axis = 0 : 열 합계
print(np_total.std(axis=0))
print(np.std(np_total, axis=0))
print()

# axis = 1 : 행 합계
print(np_total.std(axis=1))
print(np.std(np_total, axis=1))
print()

#### 최대/최소값의 index
 - argmax() / argmin()

In [ ]:
print(np_total)
print()

# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(np_total))
# 행 방향 최대값의 인덱스
print(np.argmax(np_total, axis = 0))
# 열 방향 최대값의 인덱스
print(np.argmax(np_total, axis = 1))


In [ ]:
print(np_total)
print()

# 전체 중에서 가장 큰 값의 인덱스
print(np.argmin(np_total))
# 행 방향 최대값의 인덱스
print(np.argmin(np_total, axis = 0))
# 열 방향 최대값의 인덱스
print(np.argmin(np_total, axis = 1))