# DeepLearning ( TensorFlow )
* https://www.tensorflow.org/api_docs/python/tf

## Sequential

### Linear Regression

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# tensorflow
import tensorflow as tf
from tensorflow import keras

In [25]:
x = np.array(range(0,20))
y = x * 2 - 1

x, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37]))

In [26]:
x.shape, y.shape

((20,), (20,))

In [27]:
# kears 모델 클리어
keras.backend.clear_session()

# keras 모델 선언
model = keras.models.Sequential()

In [28]:
# 모델 노드 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

# 컴파일
# loss : 예측값 평가 기준 
# optimizer : 
model.compile(loss='mse'
              , optimizer='adam')

In [29]:
# epochs : 학습 횟수
# verbose : 학습 과정 표현
model.fit(x,y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 559ms/step - loss: 319.5995
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 319.1724
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 318.7457
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 318.3192
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 317.8931
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 317.4673
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 317.0417
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 316.6165
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 316.1917
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 315.7671


In [30]:
pred = model.predict(x)
pred

1/1 [==============================] - 0s 89ms/step


array([[0.00999773],
       [0.33507058],
       [0.66014344],
       [0.98521626],
       [1.3102891 ],
       [1.635362  ],
       [1.9604348 ],
       [2.285508  ],
       [2.6105807 ],
       [2.9356534 ],
       [3.2607265 ],
       [3.5857992 ],
       [3.910872  ],
       [4.2359447 ],
       [4.561018  ],
       [4.8860908 ],
       [5.2111635 ],
       [5.5362363 ],
       [5.861309  ],
       [6.1863823 ]], dtype=float32)

### Logistic Regression

In [31]:
x = np.array(range(0,40)) 
y = np.array([0, 1] * 20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1]


In [36]:
keras.backend.clear_session()

model = keras.models.Sequential()
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy'
              , optimizer='adam'
              , metrics=['accuracy'])

In [39]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 4ms/step - loss: 14.9493 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 2ms/step - loss: 14.9286 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 5ms/step - loss: 14.9079 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 3ms/step - loss: 14.8872 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 4ms/step - loss: 14.8670 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 5ms/step - loss: 14.8468 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 4ms/step - loss: 14.8276 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 4ms/step - loss: 14.8079 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 14.7879 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 3ms/step - loss: 14.7662 - accuracy: 0.4750


In [40]:
pred = model.predict(x)
pred

2/2 [==============================] - 0s 2ms/step


array([[5.1455933e-01],
       [1.9510143e-01],
       [5.2518234e-02],
       [1.2516676e-02],
       [2.8901624e-03],
       [6.6238642e-04],
       [1.5154904e-04],
       [3.4659632e-05],
       [7.9260262e-06],
       [1.8125005e-06],
       [4.1447538e-07],
       [9.4780553e-08],
       [2.1674010e-08],
       [4.9563194e-09],
       [1.1333897e-09],
       [2.5917868e-10],
       [5.9267855e-11],
       [1.3553118e-11],
       [3.0992685e-12],
       [7.0872735e-13],
       [1.6206870e-13],
       [3.7061171e-14],
       [8.4749882e-15],
       [1.9380201e-15],
       [4.4317889e-16],
       [1.0134443e-16],
       [2.3174962e-17],
       [5.2995402e-18],
       [1.2118783e-18],
       [2.7712763e-19],
       [6.3372226e-20],
       [1.4491660e-20],
       [3.3138966e-21],
       [7.5780902e-22],
       [1.7329217e-22],
       [3.9627626e-23],
       [9.0618921e-24],
       [2.0722382e-24],
       [4.7386958e-25],
       [1.0836225e-25]], dtype=float32)

In [35]:
print(y)


[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1]


## Functional

### Linear Regression

In [41]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [42]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [43]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 249.2764
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 248.8994
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 248.5227
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 248.1462
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 247.7701
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 247.3943
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 247.0188
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 246.6436
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 246.2688
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 245.8942


In [44]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 61ms/step
[0.00999742 0.5231238  1.0362501  1.5493765  2.0625029  2.5756292
 3.0887556  3.601882   4.1150084  4.6281347  5.141261   5.6543875
 6.167514   6.68064    7.1937666  7.706893   8.220019   8.733146
 9.246272   9.759398  ]


### Logistic Regression

In [45]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [46]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [47]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 1s 554ms/step - loss: 3.1299 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 3.1272 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 3.1245 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 3.1219 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 3.1192 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 3.1165 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1138 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 3.1111 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1084 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1057 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1

### ANN ( artifical Netural Network )

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the C

In [3]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [33]:
keras.backend.clear_session()

model_seq = keras.models.Sequential()
model_seq.add(keras.layers.Input(shape=(13,)))
model_seq.add(keras.layers.Dense(32, activation='relu'))
model_seq.add(keras.layers.Dense(32, activation='relu'))
model_seq.add(keras.layers.Dense(1))

model_seq.compile(loss=keras.losses.mean_squared_error, optimizer='adam')

In [34]:
model_seq.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 629.6041
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 122.3945
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 92.9398
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 80.2723
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 76.8487
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 72.6805
Epoch 7/10
16/16 [==============================] - 0s 4ms/step - loss: 75.4335
Epoch 8/10
16/16 [==============================] - 0s 4ms/step - loss: 71.9442
Epoch 9/10
16/16 [==============================] - 0s 3ms/step - loss: 67.5253
Epoch 10/10
16/16 [==============================] - 0s 4ms/step - loss: 66.1330


In [35]:
pred_seq = model_seq.predict(x)

print(pred_seq.reshape(-1)[:5])
print()
print(y[:5])

16/16 [==============================] - 0s 2ms/step
[21.256409 25.128582 23.277723 24.889427 25.631859]

[24.  21.6 34.7 33.4 36.2]


In [40]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(13,))
hl1 = keras.layers.Dense(32, activation='relu')(il)
hl2 = keras.layers.Dense(32, activation='relu')(hl1)
ol = keras.layers.Dense(1)(hl2)


model = keras.models.Model(il, ol)
model.compile(loss=keras.losses.mean_squared_error, optimizer='adam')

In [41]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 3727.6663
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 491.2123
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 155.7201
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 96.5516
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 77.1593
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 72.1835
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 70.1752
Epoch 8/10
16/16 [==============================] - 0s 3ms/step - loss: 68.8570
Epoch 9/10
16/16 [==============================] - 0s 3ms/step - loss: 68.1512
Epoch 10/10
16/16 [==============================] - 0s 3ms/step - loss: 67.4491


In [42]:
pred = model.predict(x)

print(pred.reshape(-1)[:5])
print()
print(y[:5])

16/16 [==============================] - 0s 2ms/step
[27.711872 23.606653 23.933195 25.400702 25.370295]

[24.  21.6 34.7 33.4 36.2]


In [43]:
display(model_seq.summary())
print('*****'*15)
print('*****'*15)
display(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,537
Trainable params: 1,537
Non-trainable params: 0
_________________________________________________________________


None

***************************************************************************
***************************************************************************
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 32)                448       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,537
Trainable params: 1,537
Non-trainable params: 0
_________________________________________________________________


None

In [75]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [76]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [77]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=.1)

In [78]:
keras.backend.clear_session()

model_seq = keras.models.Sequential()
model_seq.add(keras.layers.Input(shape=(30,)))
model_seq.add(keras.layers.Dense(32, activation='relu'))
model_seq.add(keras.layers.Dense(32, activation='relu'))
model_seq.add(keras.layers.Dense(1, activation='sigmoid'))

model_seq.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics=['accuracy'])

In [79]:
model_seq.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 29.3969 - accuracy: 0.3652
Epoch 2/10
16/16 [==============================] - 0s 4ms/step - loss: 3.2204 - accuracy: 0.7070
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 1.0453 - accuracy: 0.7637
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 0.3686 - accuracy: 0.8848
Epoch 5/10
16/16 [==============================] - 0s 4ms/step - loss: 0.2852 - accuracy: 0.9082
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 0.2540 - accuracy: 0.9102
Epoch 7/10
16/16 [==============================] - 0s 4ms/step - loss: 0.1978 - accuracy: 0.9219
Epoch 8/10
16/16 [==============================] - 0s 4ms/step - loss: 0.2081 - accuracy: 0.9219
Epoch 9/10
16/16 [==============================] - 0s 4ms/step - loss: 0.2026 - accuracy: 0.9297
Epoch 10/10
16/16 [==============================] - 0s 3ms/step - loss: 0.1922 - accuracy: 0.9238


In [92]:
pred_seq = model_seq.predict(x_val)
pred_seq = np.where(pred_seq >=0.5, 1, 0)
print(pred_seq.reshape(-1))
print()
print(y_val)

2/2 [==============================] - 0s 3ms/step
[1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1
 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0]

[1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1
 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0]


In [81]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,))
hl1 = keras.layers.Dense(32, activation='relu')(il)
hl2 = keras.layers.Dense(32, activation='relu')(hl1)
ol = keras.layers.Dense(1, activation='sigmoid')(hl2)


model = keras.models.Model(il, ol)
model.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics=['accuracy'])

In [82]:
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 1s 3ms/step - loss: 5.9995 - accuracy: 0.5078
Epoch 2/10
16/16 [==============================] - 0s 5ms/step - loss: 0.9481 - accuracy: 0.6992
Epoch 3/10
16/16 [==============================] - 0s 8ms/step - loss: 0.2766 - accuracy: 0.8848
Epoch 4/10
16/16 [==============================] - 0s 5ms/step - loss: 0.2624 - accuracy: 0.8809
Epoch 5/10
16/16 [==============================] - 0s 4ms/step - loss: 0.2102 - accuracy: 0.9199
Epoch 6/10
16/16 [==============================] - 0s 4ms/step - loss: 0.2326 - accuracy: 0.9043
Epoch 7/10
16/16 [==============================] - 0s 9ms/step - loss: 0.1857 - accuracy: 0.9258
Epoch 8/10
16/16 [==============================] - 0s 8ms/step - loss: 0.1991 - accuracy: 0.9141
Epoch 9/10
16/16 [==============================] - 0s 6ms/step - loss: 0.2343 - accuracy: 0.9180
Epoch 10/10
16/16 [==============================] - 0s 6ms/step - loss: 0.1972 - accuracy: 0.9199


In [91]:
pred = model.predict(x_val)
pred = np.where(pred >=0.5, 1, 0)
print(pred.reshape(-1))
print()
print(y_val)

2/2 [==============================] - 0s 3ms/step
[1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1
 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0]

[1 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1
 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0]


In [71]:
display(model_seq.summary())
print('*****'*15)
print('*****'*15)
display(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


None

***************************************************************************
***************************************************************************
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


None

In [130]:
from sklearn.datasets import load_iris
iris = load_iris()

In [140]:
x = iris.data
y = iris.target

x.shape, y.shape

((150, 4), (150,))

In [141]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.1, random_state=2022)

In [142]:
from keras.utils import to_categorical

y_train = to_categorical(y_train, 3)
y_val = to_categorical(y_val, 3)

In [146]:
keras.backend.clear_session()

model_seq = keras.models.Sequential()
model_seq.add(keras.layers.Input(shape=(4,)))
model_seq.add(keras.layers.Dense(32, activation='relu'))
model_seq.add(keras.layers.Dense(32, activation='relu'))
model_seq.add(keras.layers.Dense(3, activation='softmax'))

model_seq.compile(loss=keras.losses.categorical_crossentropy, optimizer='adam', metrics=['accuracy'])

In [147]:
model_seq.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 1s 3ms/step - loss: 1.0698 - accuracy: 0.4667
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9759 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.9132 - accuracy: 0.6667
Epoch 4/10
5/5 [==============================] - 0s 5ms/step - loss: 0.8628 - accuracy: 0.6667
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.8220 - accuracy: 0.6963
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.7856 - accuracy: 0.8296
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.7512 - accuracy: 0.8963
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.7192 - accuracy: 0.8667
Epoch 9/10
5/5 [==============================] - 0s 5ms/step - loss: 0.6888 - accuracy: 0.8889
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.6569 - accuracy: 0.8370


In [148]:
pred_seq = model_seq.predict(x_val)

print(pred_seq.argmax(axis=1))
print()
print(y_val.argmax(axis=1))

1/1 [==============================] - 0s 116ms/step
[2 2 0 2 0 0 1 2 0 1 2 2 2 2 2]

[2 2 0 2 0 0 1 1 0 1 1 2 1 2 2]


In [149]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(4,))
h1 = keras.layers.Dense(3, activation='relu')(il)
h2 = keras.layers.Dense(3, activation='relu')(h1)
ol = keras.layers.Dense(3, activation='softmax')(h2)

model = keras.models.Model(il, ol)

model.compile(loss=keras.losses.categorical_crossentropy, optimizer='adam', metrics=['accuracy'])

In [150]:
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 1s 2ms/step - loss: 1.0922 - accuracy: 0.3481
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0905 - accuracy: 0.3407
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0889 - accuracy: 0.3556
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0876 - accuracy: 0.3852
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 1.0862 - accuracy: 0.3926
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0849 - accuracy: 0.4074
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0836 - accuracy: 0.4074
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 1.0822 - accuracy: 0.4296
Epoch 9/10
5/5 [==============================] - 0s 5ms/step - loss: 1.0809 - accuracy: 0.4667
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 1.0796 - accuracy: 0.4815


In [151]:
pred = model.predict(x_val)

print(pred.argmax(axis=1))
print()
print(y_val.argmax(axis=1))

1/1 [==============================] - 0s 84ms/step
[0 2 0 2 0 0 0 0 0 2 2 2 0 2 0]

[2 2 0 2 0 0 1 1 0 1 1 2 1 2 2]


In [153]:
display(model_seq.summary())
print('*****'*13)
print('*****'*13)
display(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


None

*****************************************************************
*****************************************************************
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 3)                 15        
                                                                 
 dense_1 (Dense)             (None, 3)                 12        
                                                                 
 dense_2 (Dense)             (None, 3)                 12        
                                                                 
Total params: 39
Trainable params: 39
Non-trainable params: 0
_________________________________________________________________


None

### ANN & MNIST(숫자 손글씨)