# DeepLearning ( TensorFlow )
* https://www.tensorflow.org/api_docs/python/tf

## Sequential

### Linear Regression

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# tensorflow
import tensorflow as tf
from tensorflow import keras


In [25]:
x = np.array(range(0,20))
y = x * 2 - 1

x, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37]))

In [26]:
x.shape, y.shape

((20,), (20,))

In [27]:
# kears 모델 클리어
keras.backend.clear_session()

# keras 모델 선언
model = keras.models.Sequential()

In [28]:
# 모델 노드 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

# 컴파일
# loss : 예측값 평가 기준 
# optimizer : 
model.compile(loss='mse'
              , optimizer='adam')

In [29]:
# epochs : 학습 횟수
# verbose : 학습 과정 표현
model.fit(x,y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 559ms/step - loss: 319.5995
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 319.1724
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 318.7457
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 318.3192
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 317.8931
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 317.4673
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 317.0417
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 316.6165
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 316.1917
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 315.7671


In [30]:
pred = model.predict(x)
pred

1/1 [==============================] - 0s 89ms/step


array([[0.00999773],
       [0.33507058],
       [0.66014344],
       [0.98521626],
       [1.3102891 ],
       [1.635362  ],
       [1.9604348 ],
       [2.285508  ],
       [2.6105807 ],
       [2.9356534 ],
       [3.2607265 ],
       [3.5857992 ],
       [3.910872  ],
       [4.2359447 ],
       [4.561018  ],
       [4.8860908 ],
       [5.2111635 ],
       [5.5362363 ],
       [5.861309  ],
       [6.1863823 ]], dtype=float32)

### Logistic Regression

In [31]:
x = np.array(range(0,40)) 
y = np.array([0, 1] * 20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1]


In [36]:
keras.backend.clear_session()

model = keras.models.Sequential()
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy'
              , optimizer='adam'
              , metrics=['accuracy'])

In [39]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 4ms/step - loss: 14.9493 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 2ms/step - loss: 14.9286 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 5ms/step - loss: 14.9079 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 3ms/step - loss: 14.8872 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 4ms/step - loss: 14.8670 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 5ms/step - loss: 14.8468 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 4ms/step - loss: 14.8276 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 4ms/step - loss: 14.8079 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 14.7879 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 3ms/step - loss: 14.7662 - accuracy: 0.4750


In [40]:
pred = model.predict(x)
pred

2/2 [==============================] - 0s 2ms/step


array([[5.1455933e-01],
       [1.9510143e-01],
       [5.2518234e-02],
       [1.2516676e-02],
       [2.8901624e-03],
       [6.6238642e-04],
       [1.5154904e-04],
       [3.4659632e-05],
       [7.9260262e-06],
       [1.8125005e-06],
       [4.1447538e-07],
       [9.4780553e-08],
       [2.1674010e-08],
       [4.9563194e-09],
       [1.1333897e-09],
       [2.5917868e-10],
       [5.9267855e-11],
       [1.3553118e-11],
       [3.0992685e-12],
       [7.0872735e-13],
       [1.6206870e-13],
       [3.7061171e-14],
       [8.4749882e-15],
       [1.9380201e-15],
       [4.4317889e-16],
       [1.0134443e-16],
       [2.3174962e-17],
       [5.2995402e-18],
       [1.2118783e-18],
       [2.7712763e-19],
       [6.3372226e-20],
       [1.4491660e-20],
       [3.3138966e-21],
       [7.5780902e-22],
       [1.7329217e-22],
       [3.9627626e-23],
       [9.0618921e-24],
       [2.0722382e-24],
       [4.7386958e-25],
       [1.0836225e-25]], dtype=float32)

In [35]:
print(y)


[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1]


## Functional

### Linear Regression

In [41]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [42]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [43]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 249.2764
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 248.8994
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 248.5227
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 248.1462
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 247.7701
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 247.3943
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 247.0188
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 246.6436
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 246.2688
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 245.8942


In [44]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 61ms/step
[0.00999742 0.5231238  1.0362501  1.5493765  2.0625029  2.5756292
 3.0887556  3.601882   4.1150084  4.6281347  5.141261   5.6543875
 6.167514   6.68064    7.1937666  7.706893   8.220019   8.733146
 9.246272   9.759398  ]


### Logistic Regression

In [45]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [46]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [47]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 1s 554ms/step - loss: 3.1299 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 3.1272 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 3.1245 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 3.1219 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 3.1192 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 3.1165 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1138 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 3.1111 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1084 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1057 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1